// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuwK5AKNAX2skSOm5RHcZbJk6Ff4Z06oI',
    appId: '1:664527327337:web:b5059527901203c90a52f8',
    messagingSenderId: '664527327337',
    projectId: 'made-ebaf4',
    authDomain: 'made-ebaf4.firebaseapp.com',
    storageBucket: 'made-ebaf4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3h_wgGFJkQSzPOoOszWMuZJ7JCcYjbck',
    appId: '1:664527327337:android:4851394aa8b971ba0a52f8',
    messagingSenderId: '664527327337',
    projectId: 'made-ebaf4',
    storageBucket: 'made-ebaf4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqifYFBQyuVtXSPXMdWRyYqfr1yxiGOQw',
    appId: '1:664527327337:ios:0e9efd5fc16f4a3d0a52f8',
    messagingSenderId: '664527327337',
    projectId: 'made-ebaf4',
    storageBucket: 'made-ebaf4.appspot.com',
    iosBundleId: 'com.example.madeFirebase',
  );
}
